const express = require('express');
const router = express.Router();
const { v4: uuidv4 } = require('uuid');
const { authenticateToken } = require('../middleware/auth');
const db = require('../config/database');

function buildTerms({ property, tenant, landlord, annualRent, serviceCharge, cautionDeposit, durationMonths, startDate }) {
  const naira = (n) => `₦${Number(n || 0).toLocaleString('en-NG')}`;
  return [
    'TENANCY AGREEMENT',
    '',
    `This agreement is made between ${landlord.first_name} ${landlord.last_name} (the "Landlord") and ${tenant.first_name} ${tenant.last_name} (the "Tenant").`,
    '',
    '1. PREMISES',
    `The Tenant shall occupy: ${property.title}, ${property.address}, ${property.city}, ${property.state}.`,
    '',
    '2. TERM',
    `The tenancy shall run for ${durationMonths} months commencing ${startDate}.`,
    '',
    '3. RENT',
    `Annual rent: ${naira(annualRent)}. Service charge: ${naira(serviceCharge)}. Caution deposit: ${naira(cautionDeposit)}.`,
    'Rent is payable in advance. Service charges and utilities are separate unless stated above.',
    '',
    '4. TENANT RESPONSIBILITIES',
    'The Tenant shall keep the premises in good condition, pay utility bills promptly, and avoid assigning the tenancy without written consent.',
    '',
    '5. LANDLORD RESPONSIBILITIES',
    'The Landlord shall maintain the structure, major installations and drains, and give reasonable notice before inspection.',
    '',
    '6. NOTICES',
    'Either party may give notice at the contact details registered on House Matters.',
    '',
    'Agreed by both parties. Generated by House Matters.',
  ].join('\n');
}

// GET /api/agreements — agreements involving the current user
router.get('/', authenticateToken, async (req, res) => {
  try {
    const rows = await db.query(
      `SELECT a.*, p.title as property_title, p.address, p.city, p.state,
              t.first_name || ' ' || t.last_name as tenant_name,
              l.first_name || ' ' || l.last_name as landlord_name
       FROM agreements a
       JOIN properties p ON a.property_id = p.id
       JOIN users t ON a.tenant_id = t.id
       JOIN users l ON a.landlord_id = l.id
       WHERE a.tenant_id = ? OR a.landlord_id = ?
       ORDER BY a.created_at DESC`,
      [req.user.userId, req.user.userId],
    ).rows;
    res.json({ success: true, data: { agreements: rows } });
  } catch (error) {
    console.error('Get agreements error:', error);
    res.status(500).json({ success: false, error: { code: 'SERVER_ERROR', message: 'Could not load agreements' } });
  }
});

// POST /api/agreements — landlord creates an agreement from a booking
router.post('/', authenticateToken, async (req, res) => {
  try {
    const { bookingId, serviceCharge = 0, cautionDeposit = 0, durationMonths = 12 } = req.body;
    if (!bookingId) {
      return res.status(400).json({ success: false, error: { code: 'MISSING_FIELD', message: 'bookingId is required' } });
    }

    const booking = await db.query(
      `SELECT b.*, p.landlord_id, p.title, p.address, p.city, p.state, p.rent
       FROM bookings b JOIN properties p ON b.property_id = p.id WHERE b.id = ?`,
      [bookingId],
    ).rows[0];
    if (!booking) {
      return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Booking not found' } });
    }
    if (booking.landlord_id !== req.user.userId) {
      return res.status(403).json({ success: false, error: { code: 'NOT_AUTHORIZED', message: 'Only the property owner can create an agreement' } });
    }
    if (!['confirmed', 'completed'].includes(booking.status)) {
      return res.status(400).json({ success: false, error: { code: 'INVALID_STATUS', message: 'Confirm the booking before creating an agreement' } });
    }

    const existing = await db.query('SELECT id FROM agreements WHERE booking_id = ?', [bookingId]);
    if (existing.rows.length > 0) {
      return res.status(409).json({ success: false, error: { code: 'ALREADY_EXISTS', message: 'An agreement already exists for this booking' } });
    }

    const tenant = await db.query('SELECT * FROM users WHERE id = ?', [booking.tenant_id]).rows[0];
    const landlord = await db.query('SELECT * FROM users WHERE id = ?', [req.user.userId]).rows[0];

    const terms = buildTerms({
      property: { title: booking.title, address: booking.address, city: booking.city, state: booking.state },
      tenant, landlord,
      annualRent: booking.rent,
      serviceCharge, cautionDeposit,
      durationMonths, startDate: booking.requested_date,
    });

    const id = uuidv4();
    await db.query(
      `INSERT INTO agreements (id, booking_id, tenant_id, landlord_id, property_id, annual_rent, service_charge, caution_deposit, duration_months, start_date, terms, status)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'sent')`,
      [id, bookingId, booking.tenant_id, req.user.userId, booking.property_id, booking.rent, serviceCharge, cautionDeposit, durationMonths, booking.requested_date, terms],
    );

    const row = await db.query('SELECT * FROM agreements WHERE id = ?', [id]).rows[0];
    res.status(201).json({ success: true, data: { agreement: row } });
  } catch (error) {
    console.error('Create agreement error:', error);
    res.status(500).json({ success: false, error: { code: 'SERVER_ERROR', message: 'Could not create agreement' } });
  }
});

// PUT /api/agreements/:id/status — tenant signs, either party voids
router.put('/:id/status', authenticateToken, async (req, res) => {
  try {
    const { status } = req.body;
    if (!['draft', 'sent', 'signed', 'void'].includes(status)) {
      return res.status(400).json({ success: false, error: { code: 'INVALID_STATUS', message: 'Invalid status' } });
    }
    const agreement = await db.query('SELECT * FROM agreements WHERE id = ?', [req.params.id]).rows[0];
    if (!agreement) {
      return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Agreement not found' } });
    }
    if (agreement.tenant_id !== req.user.userId && agreement.landlord_id !== req.user.userId) {
      return res.status(403).json({ success: false, error: { code: 'NOT_AUTHORIZED', message: 'Not a party to this agreement' } });
    }
    if (status === 'signed' && agreement.tenant_id !== req.user.userId) {
      return res.status(403).json({ success: false, error: { code: 'NOT_AUTHORIZED', message: 'Only the tenant can sign' } });
    }
    await db.query('UPDATE agreements SET status = ? WHERE id = ?', [status, req.params.id]);
    const row = await db.query('SELECT * FROM agreements WHERE id = ?', [req.params.id]).rows[0];
    res.json({ success: true, data: { agreement: row } });
  } catch (error) {
    console.error('Update agreement error:', error);
    res.status(500).json({ success: false, error: { code: 'SERVER_ERROR', message: 'Could not update agreement' } });
  }
});

// GET /api/agreements/:id/print — plain-text agreement for download/print
router.get('/:id/print', authenticateToken, async (req, res) => {
  try {
    const row = await db.query(
      `SELECT a.*, p.title as property_title, p.address, p.city, p.state
       FROM agreements a JOIN properties p ON a.property_id = p.id WHERE a.id = ?`,
      [req.params.id],
    ).rows[0];
    if (!row) {
      return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Agreement not found' } });
    }
    if (row.tenant_id !== req.user.userId && row.landlord_id !== req.user.userId) {
      return res.status(403).json({ success: false, error: { code: 'NOT_AUTHORIZED', message: 'Not a party to this agreement' } });
    }
    res.type('text/plain').send(row.terms || '');
  } catch (error) {
    console.error('Print agreement error:', error);
    res.status(500).json({ success: false, error: { code: 'SERVER_ERROR', message: 'Could not load agreement' } });
  }
});

module.exports = router;
module.exports.buildTerms = buildTerms;
