// Sample listing data for the House Matters demo UI.
// Every entry is illustrative: photos are illustrative and prices are sample annual rents.

export type Property = {
  id: string;
  title: string;
  price: number;
  location: string;
  type: 'apartment' | 'house' | 'studio';
  features: string[];
  image: string;
  alt: string;
  badge?: string;
  agency?: string;
  description: string;
  /** Floor area + amenity extras shown only in the detail modal. */
  area?: string;
  amenities?: string[];
  landlordId?: string;
};

export function formatNaira(value: number): string {
  return new Intl.NumberFormat('en-NG', {
    style: 'currency',
    currency: 'NGN',
    maximumFractionDigits: 0,
  }).format(value);
}

export const properties: Property[] = [
  {
    id: 'lekki-flat',
    title: 'Bright 2-bedroom flat',
    price: 4500000,
    location: 'Lekki Phase 1, Lagos',
    type: 'apartment',
    features: ['2 bedrooms', '2 bathrooms', 'Balcony'],
    image: '/images/living-room.jpg',
    alt: 'Illustrative airy living room with neutral furnishings',
    badge: 'Featured',
    description: 'A sample two-bedroom layout for your Lekki home search. Ask about service charges, power arrangements, water supply and parking during an inspection.',
  },
  {
    id: 'yaba-studio',
    title: 'Cosy self-contained studio',
    price: 1200000,
    location: 'Yaba, Lagos',
    type: 'studio',
    features: ['Self-contained', '1 bathroom', 'Kitchenette'],
    image: '/images/apartment.jpg',
    alt: 'Illustrative compact apartment with a bright living space',
    badge: 'Compact living',
    description: 'An example of a self-contained home for independent living. Confirm the exact street, transport options, water supply and all move-in costs before committing.',
  },
  {
    id: 'gwarinpa-duplex',
    title: 'Spacious family duplex',
    price: 6500000,
    location: 'Gwarinpa, Abuja',
    type: 'house',
    features: ['4 bedrooms', '4 bathrooms', 'Parking'],
    image: '/images/home-exterior.jpg',
    alt: 'Illustrative contemporary home exterior with landscaped grounds',
    badge: 'Family pick',
    description: 'A sample family duplex for your Abuja search. Check estate rules, security arrangements, drainage and maintenance responsibilities with the owner.',
  },
  {
    id: 'ikeja-flat',
    title: 'A little more room to unwind',
    price: 3800000,
    location: 'Ikeja GRA, Lagos',
    type: 'apartment',
    features: ['3 bedrooms', '3 bathrooms', 'Living room'],
    image: '/images/bedroom.jpg',
    alt: 'Illustrative bedroom with warm textiles and natural light',
    description: 'An illustrative three-bedroom flat. Discuss commute times, electricity metering and any separate estate or service charges before arranging a tenancy.',
  },
  {
    id: 'wuse-flat',
    title: 'Contemporary city apartment',
    price: 5200000,
    location: 'Wuse 2, Abuja',
    type: 'apartment',
    features: ['2 bedrooms', '2 bathrooms', 'Dining area'],
    image: '/images/living-room.jpg',
    alt: 'Illustrative contemporary open-plan living area',
    description: 'A sample city apartment to help compare layouts and budgets. Confirm what is included in the quoted annual rent and request a written breakdown of other costs.',
  },
  {
    id: 'ibadan-house',
    title: 'A calm place to call home',
    price: 2400000,
    location: 'Bodija, Ibadan',
    type: 'house',
    features: ['3 bedrooms', '2 bathrooms', 'Compound'],
    image: '/images/home-exterior.jpg',
    alt: 'Illustrative detached house surrounded by greenery',
    badge: 'Family pick',
    description: 'An example family home for a Bodija search. Inspect the compound, access road, drainage and water storage, and confirm who handles repairs.',
  },
  {
    id: 'port-harcourt-flat',
    title: 'Light-filled 3-bedroom flat',
    price: 3200000,
    location: 'GRA Phase 2, Port Harcourt',
    type: 'apartment',
    features: ['3 bedrooms', '3 bathrooms', 'Balcony'],
    image: '/images/apartment.jpg',
    alt: 'Illustrative sunlit apartment with a dining corner',
    description: 'A sample three-bedroom flat. Visit the neighbourhood, ask about flooding and power supply, and verify the person authorised to let the property.',
  },
  {
    id: 'enugu-studio',
    title: 'Your own comfortable corner',
    price: 850000,
    location: 'Independence Layout, Enugu',
    type: 'studio',
    features: ['Self-contained', '1 bathroom', 'Kitchenette'],
    image: '/images/bedroom.jpg',
    alt: 'Illustrative bedroom with simple contemporary furniture',
    description: 'An example self-contained home for a smaller household. Check ventilation, water access and the total initial payment, not only the annual rent.',
  },
  {
    id: 'ajah-duplex',
    title: 'Room for the whole family',
    price: 4000000,
    location: 'Ajah, Lagos',
    type: 'house',
    features: ['4 bedrooms', '4 bathrooms', 'Parking'],
    image: '/images/home-exterior.jpg',
    alt: 'Illustrative modern family home with outdoor space',
    description: 'A sample duplex for an Ajah search. Visit at different times to assess traffic and ask about drainage, estate charges and electricity arrangements.',
  },
  {
    id: 'kano-flat',
    title: 'Simple, spacious everyday living',
    price: 1800000,
    location: 'Nassarawa GRA, Kano',
    type: 'apartment',
    features: ['2 bedrooms', '2 bathrooms', 'Living room'],
    image: '/images/living-room.jpg',
    alt: 'Illustrative spacious living room with comfortable seating',
    description: 'An example two-bedroom flat. Inspect in person, confirm ownership or authority to let, and agree rent, repairs and any additional charges in writing.',
  },
  // ——— Luxury collection: illustrative premium listings from Lagos & Abuja ———
  {
    id: 'banana-island-penthouse',
    title: 'Waterfront penthouse with jetty views',
    price: 85000000,
    location: 'Banana Island, Ikoyi, Lagos',
    type: 'apartment',
    features: ['4 bedrooms', '5 bathrooms', 'Private jetty', 'Smart home'],
    image: '/images/penthouse.jpg',
    alt: 'Illustrative luxury penthouse interior with floor-to-ceiling windows',
    badge: 'Luxury',
    agency: 'Sujimoto Group',
    description: 'An illustrative penthouse in Nigeria’s most exclusive enclave. Verify service charges, security arrangements, facility management terms and jetty access rights before committing.',
  },
  {
    id: 'ikoyi-luxury-condo',
    title: 'Designer condo off Bourdillon',
    price: 45000000,
    location: 'Ikoyi, Lagos',
    type: 'apartment',
    features: ['3 bedrooms', '4 bathrooms', 'Gym & pool', 'Concierge'],
    image: '/images/luxury-condo.jpg',
    alt: 'Illustrative high-end condominium living space with designer finishes',
    badge: 'Luxury',
    agency: 'Grenadines Homes',
    description: 'A sample premium condo for an Ikoyi search. Confirm facility fees, generator and power arrangements, and the estate’s rental policy with the developer’s representatives.',
  },
  {
    id: 'vi-skyline-residence',
    title: 'Skyline residence above the Island',
    price: 95000000,
    location: 'Adeola Odeku, Victoria Island, Lagos',
    type: 'apartment',
    features: ['4 bedrooms', '5 bathrooms', 'Rooftop lounge', 'Panoramic views'],
    image: '/images/skyline-villa.jpg',
    alt: 'Illustrative high-rise residence overlooking the city skyline',
    badge: 'Luxury',
    agency: 'Mixta Africa',
    description: 'A sample high-rise residence with skyline views. Confirm elevator service, power redundancy, parking allocation and the full breakdown of annual service charges.',
  },
  {
    id: 'oniru-modern-villa',
    title: 'Architect-designed smart villa',
    price: 60000000,
    location: 'Oniru, Victoria Island, Lagos',
    type: 'house',
    features: ['5 bedrooms', '6 bathrooms', 'Home cinema', 'Staff quarters'],
    image: '/images/modern-villa.jpg',
    alt: 'Illustrative contemporary villa facade with clean architectural lines',
    badge: 'Luxury',
    agency: 'Landwey',
    description: 'An illustrative smart villa for a Victoria Island search. Ask about drainage, security protocols, estate charges and what the quoted rent includes.',
  },
  {
    id: 'maitama-hilltop-villa',
    title: 'Ambassadorial hilltop mansion',
    price: 70000000,
    location: 'Maitama, Abuja',
    type: 'house',
    features: ['6 bedrooms', '7 bathrooms', 'Swimming pool', 'Guest chalet'],
    image: '/images/hilltop-villa.jpg',
    alt: 'Illustrative grand villa on an elevated, landscaped plot',
    badge: 'Luxury',
    agency: 'Brains & Hammers',
    description: 'An illustrative Maitama mansion for diplomatic-scale living. Verify security arrangements, estate rules, maintenance responsibilities and payment terms in writing.',
  },
  {
    id: 'asokoro-garden-villa',
    title: 'Serene garden villa near Aso Rock',
    price: 55000000,
    location: 'Asokoro, Abuja',
    type: 'house',
    features: ['5 bedrooms', '6 bathrooms', 'Landscaped gardens', 'Borehole & solar'],
    image: '/images/garden-villa.jpg',
    alt: 'Illustrative villa surrounded by manicured gardens',
    badge: 'Luxury',
    agency: 'Cosgrove Investment Partners',
    description: 'A sample garden villa in a serene Asokoro setting. Ask about solar and water infrastructure, security, and who handles landscape and facility maintenance.',
  },
  {
    id: 'guzape-smart-townhouse',
    title: 'Contemporary smart townhouse',
    price: 35000000,
    location: 'Guzape District, Abuja',
    type: 'house',
    features: ['4 bedrooms', '5 bathrooms', 'Home automation', 'Terrace'],
    image: '/images/townhouse.jpg',
    alt: 'Illustrative modern townhouse with a private terrace',
    badge: 'Luxury',
    agency: 'Adron Homes',
    description: 'An illustrative smart townhouse in the growing Guzape district. Confirm road access, estate development status, service charges and handover condition before paying.',
  },
  {
    id: 'jabi-lakeside-residence',
    title: 'Lakeside residence with water views',
    price: 28000000,
    location: 'Jabi, Abuja',
    type: 'apartment',
    features: ['3 bedrooms', '4 bathrooms', 'Lake view', 'Gym & pool'],
    image: '/images/luxury-condo.jpg',
    alt: 'Illustrative elegant apartment with a view towards the lake',
    badge: 'Luxury',
    agency: 'UPDC',
    description: 'A sample lakeside apartment near Jabi Lake. Verify facility management quality, power and water reliability, parking and all fees beyond the quoted rent.',
  },
];
